apps:
  - name: cms
    script: /usr/local/bin/npm
    cwd: ./femidacms
    args: run develop
    watch: ['cms']
    instances: 1
  - name: landing
    script: /usr/local/bin/serve
    args: -s femidamurino.ru/build -l 3001
    watch: ['landing']
    instances: 1
    env:
      NODE_ENV: production